const KEY='apf_scoreboard_v2';
const blank='';
const baseState={eventName:'TORNEO APERTURA APF',category:'Suma 11 Masculino',court:'Cancha 1',matchState:'CALENTAMIENTO',goldenPoint:true,logo:'',serve:'A',winner:'',teamA:{name:'PAREJA A',players:[{name:'Jugador A1',photo:''},{name:'Jugador A2',photo:''}],points:0,games:[0,0,0],sets:0},teamB:{name:'PAREJA B',players:[{name:'Jugador B1',photo:''},{name:'Jugador B2',photo:''}],points:0,games:[0,0,0],sets:0},currentSet:0};
function load(){try{return {...structuredClone(baseState),...(JSON.parse(localStorage.getItem(KEY))||{})}}catch(e){return structuredClone(baseState)}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new Event('storage'))}
function imgToData(input){return new Promise(res=>{const f=input.files&&input.files[0];if(!f)return res(null);const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(f)})}
function initials(n){return (n||'APF').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'APF'}
function pointLabel(n,golden){const arr=golden?['0','15','30','40','ORO']:['0','15','30','40','AD'];return arr[Math.min(n,arr.length-1)]}
function renderAll(){document.querySelectorAll('.scoreboard').forEach(el=>render(el,load()))}
function render(el,s){const A=s.teamA,B=s.teamB;el.innerHTML=`<div class="score-inner"><div class="score-head"><div class="brand"><div class="logo">${s.logo?`<img src="${s.logo}" style="width:100%;height:100%;object-fit:cover;border-radius:18px">`:'APF'}</div><div class="event"><small>${s.category||''} · ${s.court||''}</small><br><b>${s.eventName||'Marcador APF'}</b></div></div><div class="pill">${s.matchState||'EN JUEGO'}</div></div><div class="score-body">${teamHtml('A',A,s)}<div class="center"><div class="vs">VS</div><div class="state">SETS</div><div class="sets-big">${A.sets} - ${B.sets}</div><table class="games-table"><tr><th></th><th>S1</th><th>S2</th><th>S3</th></tr><tr><td>A</td>${A.games.map(x=>`<td>${x}</td>`).join('')}</tr><tr><td>B</td>${B.games.map(x=>`<td>${x}</td>`).join('')}</tr></table><div class="state">Saque: ${s.serve==='A'?A.name:B.name}</div></div>${teamHtml('B',B,s)}</div>${s.winner?`<div class="winner">GANADOR: ${s.winner}</div>`:''}</div>`}
function teamHtml(side,t,s){return `<section class="team ${s.serve===side?'active':''}"><div class="team-name">${t.name}</div><div class="players">${t.players.map(p=>`<div class="player">${p.photo?`<img class="photo" src="${p.photo}">`:`<div class="photo ph">${initials(p.name)}</div>`}<div class="pname">${p.name}</div></div>`).join('')}</div><div class="points">${pointLabel(t.points,s.goldenPoint)}</div></section>`}
function winPoint(side){let s=load(),me=s['team'+side],op=s['team'+(side==='A'?'B':'A')];me.points++; if(me.points>=4){winGame(side,s)} save(s);renderAll()}
function winGame(side,s){let me=s['team'+side],op=s['team'+(side==='A'?'B':'A')],cs=s.currentSet;me.points=0;op.points=0;me.games[cs]++;s.serve=s.serve==='A'?'B':'A';if(me.games[cs]>=6 && me.games[cs]-op.games[cs]>=2){me.sets++;s.currentSet=Math.min(2,s.currentSet+1);if(me.sets>=2){s.winner=me.name;s.matchState='FINALIZADO'}}}
function undoPoint(side){let s=load(),me=s['team'+side];me.points=Math.max(0,me.points-1);save(s);renderAll()}
function addGame(side,delta){let s=load(),me=s['team'+side];me.games[s.currentSet]=Math.max(0,me.games[s.currentSet]+Number(delta));save(s);renderAll()}
async function initOperator(){let s=load();renderAll();for(const [id,val] of [['eventName',s.eventName],['category',s.category],['court',s.court],['teamAName',s.teamA.name],['teamBName',s.teamB.name],['a1',s.teamA.players[0].name],['a2',s.teamA.players[1].name],['b1',s.teamB.players[0].name],['b2',s.teamB.players[1].name]]){const e=document.getElementById(id);if(e)e.value=val}document.getElementById('matchState').value=s.matchState;document.getElementById('goldenPoint').checked=!!s.goldenPoint;document.getElementById('setupForm').onsubmit=async e=>{e.preventDefault();let s=load();Object.assign(s,{eventName:eventName.value,category:category.value,court:court.value,matchState:matchState.value,goldenPoint:goldenPoint.checked});s.teamA.name=teamAName.value;s.teamB.name=teamBName.value;s.teamA.players[0].name=a1.value;s.teamA.players[1].name=a2.value;s.teamB.players[0].name=b1.value;s.teamB.players[1].name=b2.value;const files=[['logo',logoFile],['a10',a1Photo],['a21',a2Photo],['b10',b1Photo],['b21',b2Photo]];for(const [k,input] of files){const data=await imgToData(input);if(data){if(k==='logo')s.logo=data; if(k==='a10')s.teamA.players[0].photo=data;if(k==='a21')s.teamA.players[1].photo=data;if(k==='b10')s.teamB.players[0].photo=data;if(k==='b21')s.teamB.players[1].photo=data;}}save(s);renderAll()};document.querySelectorAll('[data-point]').forEach(b=>b.onclick=()=>winPoint(b.dataset.point));document.querySelectorAll('[data-undo]').forEach(b=>b.onclick=()=>undoPoint(b.dataset.undo));document.querySelectorAll('[data-serve]').forEach(b=>b.onclick=()=>{let s=load();s.serve=b.dataset.serve;save(s);renderAll()});document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>addGame(b.dataset.side,b.dataset.game));resetPoints.onclick=()=>{let s=load();s.teamA.points=0;s.teamB.points=0;save(s);renderAll()};clearWinner.onclick=()=>{let s=load();s.winner='';s.matchState='EN JUEGO';save(s);renderAll()};resetAll.onclick=()=>{if(confirm('¿Reiniciar marcador completo?')){localStorage.removeItem(KEY);renderAll();location.reload()}}}
function initPublic(){renderAll();setInterval(renderAll,700);window.addEventListener('storage',renderAll)}
