
(function(){
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const configured=()=>window.APF_SUPABASE_URL&&!String(window.APF_SUPABASE_URL).includes("PEGAR_")&&window.APF_SUPABASE_ANON_KEY&&!String(window.APF_SUPABASE_ANON_KEY).includes("PEGAR_");
  const sb=()=>configured()&&window.supabase?window.supabase.createClient(window.APF_SUPABASE_URL,window.APF_SUPABASE_ANON_KEY):null;
  function status(t,ok){const e=$("status");if(e){e.className="status "+(ok?"ok":"bad");e.textContent=t;}}
  function compText(c){return `${c.type||"Torneo"} · ${c.branch||""} · ${c.category||"Sin categoría"}`;}
  async function comps(publicOnly=false){const c=sb();if(!c){status("Base online no configurada: pegá Supabase URL y ANON KEY en config.js.",false);return [];}let q=c.from("competitions").select("*").order("created_at",{ascending:false});if(publicOnly)q=q.eq("is_public",true);const {data,error}=await q;if(error){status("Error: "+error.message,false);return [];}status("Conectado a Supabase · Competencias: "+data.length,true);return data||[];}
  async function pairs(compId){const c=sb();if(!c)return [];const {data,error}=await c.from("pairs").select("*").eq("competition_id",compId).order("created_at",{ascending:false});if(error){alert(error.message);return [];}return data||[];}
  function compCard(c,admin=false){return `<div class="item"><b>${esc(c.name)}</b><span>${esc(compText(c))}</span><span>Estado: ${esc(c.status)} · ${c.is_public?"Pública":"Oculta"}</span>${c.start_date?`<span>Fecha: ${esc(c.start_date)}</span>`:""}${c.venue?`<span>Sede: ${esc(c.venue)}</span>`:""}<span class="badge">Competencia APF</span>${admin?`<div class="row"><button class="btn small primary" data-act="view" data-id="${esc(c.id)}">Ver</button><button class="btn small" data-act="edit" data-id="${esc(c.id)}">Editar</button><button class="btn small warn" data-act="toggle" data-id="${esc(c.id)}">${c.is_public?"Ocultar":"Publicar"}</button><button class="btn small danger" data-act="delete" data-id="${esc(c.id)}">Eliminar</button></div>`:""}</div>`;}
  function pairCard(p){return `<div class="item"><b>${esc(p.pair_name)}</b><span>${esc(p.player1)} / ${esc(p.player2)}</span><span>${esc(p.status)}</span>${p.phone?`<span>Tel: ${esc(p.phone)}</span>`:""}</div>`;}
  async function renderAdmin(){
    if(!$("adminApp"))return;
    if(sessionStorage.getItem("apf_admin_ok")!=="1"){
      $("adminApp").innerHTML=`<div class="login"><div class="card loginBox"><h2>Admin APF</h2><p>Usuario inicial admin · clave APF2026</p><div class="field"><label>Usuario</label><input id="loginUser" value="admin"></div><div class="field"><label>Contraseña</label><input id="loginPass" type="password"></div><div class="row"><button id="loginBtn" class="btn primary">Entrar</button></div></div></div>`;
      $("loginBtn").onclick=()=>{if($("loginUser").value.trim()===window.APF_ADMIN_USER&&$("loginPass").value.trim()===window.APF_ADMIN_PASS){sessionStorage.setItem("apf_admin_ok","1");renderAdmin();}else alert("Usuario o contraseña incorrectos");};
      return;
    }
    $("adminApp").innerHTML=`<div class="wrap"><div class="header"><div class="brand"><div class="logo">APF</div><div><h1>Admin APF Real</h1><p>Competencias y parejas con base online.</p></div></div><div class="nav"><a class="btn" href="publico.html" target="_blank">Ver público</a><a class="btn" href="planillero.html">Planillero</a><a class="btn" href="tv.html">TV</a><button id="logout" class="btn danger">Salir</button></div></div><div id="status" class="status">Conectando...</div><div class="card"><h2>Crear competencia</h2><p>Lo guardado acá debe aparecer también en Público.</p><div class="tabs"><button class="chip active" data-branch="Masculino">Masculino</button><button class="chip" data-branch="Femenino">Femenino</button><button class="chip" data-branch="Mixto">Mixto</button></div><div class="tabs"><button class="chip active" data-type="Torneo">Torneo</button><button class="chip" data-type="Liga">Liga</button></div><div class="grid"><div class="field"><label>Nombre competencia</label><input id="name" placeholder="Torneo Apertura 2026"></div><div class="field"><label>Categoría libre</label><input id="category" placeholder="Suma 13, Damas B"></div><div class="field"><label>Estado</label><select id="statusComp"><option>Inscripción abierta</option><option>Próxima</option><option>En juego</option><option>Finalizada</option></select></div><div class="field"><label>Fecha inicio</label><input id="startDate" type="date"></div><div class="field"><label>Sede</label><input id="venue" placeholder="Complejo APF"></div><div class="field"><label>Inscripción</label><input id="inscription" placeholder="$"></div><div class="field"><label>Premio</label><input id="prize" placeholder="$ / trofeo"></div><div class="field"><label>Formato</label><select id="format"><option>Zonas + Playoffs</option><option>Liga</option><option>Eliminación directa</option><option>Liga + Playoffs</option></select></div><div class="field"><label>Playoffs desde</label><select id="playoffs"><option>Sin playoffs</option><option>Final</option><option>Semifinal</option><option>Cuartos de final</option><option>Octavos de final</option><option>16avos de final</option></select></div><div class="field" style="grid-column:1/-1"><label>Descripción</label><textarea id="description"></textarea></div></div><div class="tabs">${["Suma 9","Suma 11","Suma 13","Suma 15","8va","7ma","6ta"].map(x=>`<button class="chip" data-cat="${x}">${x}</button>`).join("")}</div><div class="row"><button id="saveComp" class="btn primary">Guardar competencia</button></div></div><div class="card"><h2>Competencias creadas</h2><div id="competitionsList" class="list"></div></div><div class="card" id="detailCard"><h2>Detalle / Parejas</h2><div id="detail" class="empty">Tocá Ver en una competencia.</div></div><div class="footer">Agrupación Pádel Friense · Sistema Real v1</div></div>`;
    $("logout").onclick=()=>{sessionStorage.removeItem("apf_admin_ok");renderAdmin();};
    let branch="Masculino",type="Torneo";
    document.querySelectorAll("[data-branch]").forEach(b=>b.onclick=()=>{branch=b.dataset.branch;document.querySelectorAll("[data-branch]").forEach(x=>x.classList.remove("active"));b.classList.add("active");});
    document.querySelectorAll("[data-type]").forEach(b=>b.onclick=()=>{type=b.dataset.type;document.querySelectorAll("[data-type]").forEach(x=>x.classList.remove("active"));b.classList.add("active");});
    document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>$("category").value=b.dataset.cat);
    async function refresh(){const list=await comps(false);$("competitionsList").innerHTML=list.length?list.map(c=>compCard(c,true)).join(""):`<div class="empty">No hay competencias creadas.</div>`;document.querySelectorAll("[data-act]").forEach(b=>b.onclick=()=>act(b.dataset.act,b.dataset.id));}
    async function act(a,id){const c=sb();if(!c)return alert("Configurar Supabase primero.");if(a==="view")return detail(id);if(a==="delete"){if(!confirm("¿Eliminar?"))return;await c.from("competitions").delete().eq("id",id);return refresh();}const list=await comps(false);const comp=list.find(x=>x.id===id);if(!comp)return;if(a==="toggle"){await c.from("competitions").update({is_public:!comp.is_public}).eq("id",id);return refresh();}if(a==="edit"){const name=prompt("Nombre",comp.name)||comp.name;const category=prompt("Categoría",comp.category||"");await c.from("competitions").update({name,category}).eq("id",id);return refresh();}}
    async function detail(id){const c=sb();const {data:comp,error}=await c.from("competitions").select("*").eq("id",id).single();if(error)return alert(error.message);const ps=await pairs(id);$("detail").className="";$("detail").innerHTML=`<div class="item"><b>${esc(comp.name)}</b><span>${esc(compText(comp))}</span></div><hr><h3>Cargar pareja</h3><div class="grid"><div class="field"><label>Nombre pareja</label><input id="pairName"></div><div class="field"><label>Jugador 1</label><input id="player1"></div><div class="field"><label>Jugador 2</label><input id="player2"></div><div class="field"><label>Teléfono</label><input id="phone"></div><div class="field"><label>Estado</label><select id="pairStatus"><option>Confirmada</option><option>Pendiente</option><option>Baja</option></select></div></div><div class="row"><button id="savePair" class="btn primary">Guardar pareja</button></div><h3>Parejas cargadas</h3><div class="list">${ps.length?ps.map(pairCard).join(""):`<div class="empty">Sin parejas.</div>`}</div>`;$("savePair").onclick=async()=>{await c.from("pairs").insert({competition_id:id,pair_name:$("pairName").value.trim()||"Pareja APF",player1:$("player1").value.trim()||"Jugador 1",player2:$("player2").value.trim()||"Jugador 2",phone:$("phone").value.trim(),status:$("pairStatus").value});detail(id);};$("detailCard").scrollIntoView({behavior:"smooth"});}
    $("saveComp").onclick=async()=>{const c=sb();if(!c)return alert("Primero configurá Supabase en config.js");const {error}=await c.from("competitions").insert({name:$("name").value.trim()||"Competencia APF",branch,type,category:$("category").value.trim(),status:$("statusComp").value,start_date:$("startDate").value||null,venue:$("venue").value.trim(),inscription:$("inscription").value.trim(),prize:$("prize").value.trim(),format:$("format").value,playoffs:$("playoffs").value,description:$("description").value.trim(),is_public:true});if(error)return alert(error.message);alert("Competencia guardada en base online");refresh();};
    refresh();
  }
  async function renderPublic(){if(!$("publicApp"))return;$("publicApp").innerHTML=`<div class="wrap"><div class="header"><div class="brand"><div class="logo">APF</div><div><h1>Agrupación Pádel Friense</h1><p>Toda la actividad del pádel friense en un solo lugar.</p></div></div><div class="nav"><a class="btn" href="admin.html">Admin</a></div></div><div id="status" class="status">Conectando...</div><div class="card"><h2>Competencias APF</h2><p>Competencias publicadas desde Admin.</p><div id="publicCompetitions" class="list"></div></div><div class="footer">WhatsApp Sebastián: 3854693517 · Jeremías: 3854400216</div></div>`;const list=await comps(true);$("publicCompetitions").innerHTML=list.length?list.map(c=>compCard(c,false)).join(""):`<div class="empty">No hay competencias visibles.</div>`;}
  function simple(id,title){if(!$(id))return;$(id).innerHTML=`<div class="wrap"><div class="header"><div class="brand"><div class="logo">APF</div><div><h1>${title}</h1><p>Próximo módulo a conectar con Supabase.</p></div></div><div class="nav"><a class="btn" href="publico.html">Público</a><a class="btn" href="admin.html">Admin</a></div></div><div class="card"><h2>En construcción</h2><p>Primero dejamos funcionando Competencias + Parejas + Público con base online real.</p></div></div>`;}
  document.addEventListener("DOMContentLoaded",()=>{renderAdmin();renderPublic();simple("planilleroApp","Planillero APF");simple("tvApp","TV APF");simple("rankingApp","Ranking APF");});
})();
